
set -u
cd "$(dirname "$0")"
PY="${PYTHON:-$(command -v python || command -v python3)}"

TASKS=(
  "get the information on seller sku SYN-261-38X"
  "what is the price of SYN-142-21T?"
  "which products are made by RecallFlex Medical AG?"
  "how many products are in the catalogue?"
  "what is the GTIN of SYN-100-15S?"
)

{
  echo "# Transcript"
  echo
  echo "Real terminal output of the client for the five assignment tasks, default settings"
  echo "(LLM question parser). Generated by \`make_transcript.sh\` on $(date '+%Y-%m-%d %H:%M %Z'); not edited."
  echo
  for t in "${TASKS[@]}"; do
    echo '```text'
    echo "\$ python -m corpus_client --task \"$t\""
    "$PY" -m corpus_client --task "$t" 2>&1
    echo "[exit code $?]"
    echo '```'
    echo
  done
} > transcript.md

echo "Wrote transcript.md"

# Consistency check: ANSWERS.md Q2 must quote the transcript's first answer exactly.
"${CHECK_PY:-$PY}" - <<'PYEOF'
import re
blocks = re.findall(r"```text\n\$ [^\n]*\n(.*?)\[exit code", open("transcript.md").read(), re.S)
first = blocks[0].strip() if blocks else ""
if first and first in open("ANSWERS.md").read():
    print("OK: ANSWERS.md Q2 matches the transcript exactly.")
else:
    print("MISMATCH: copy the first transcript block into ANSWERS.md Q2 (or ask Claude).")
PYEOF
